apiVersion: v1
kind: Service
metadata:
  name: dashbtc
spec:
  selector:
    app: dashbtc
  ports:
    - protocol: TCP
      port: 3000  # Porta interna do serviço
      targetPort: 3000  # Porta que o contêiner Node.js está ouvindo
  type: NodePort

